[package]
name = "rpc"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"
path = "src/task/client/main.rs"

[[bin]]
name = "server"
path = "src/task/server/main.rs"

[dependencies]
prost = "0.14.4"
prost-wkt = "0.7.2"
prost-wkt-types = "0.7.2"
serde = "1.0.229"
serde_json = "1.0.151"

[build-dependencies]                                                                                                    
prost-build = "0.14.4"
